<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/MasterPage.Master" CodeBehind="FinishForm.aspx.vb" Inherits="BL.QuoteMachine.FinishForm" %>

<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="styles/grid.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <telerik:RadPageLayout runat="server" ID="JumbotronLayout" CssClass="jumbotron" GridType="Fluid">
        <Rows>
            <telerik:LayoutRow>
                <Columns>
                    <telerik:LayoutColumn Span="10" SpanMd="12" SpanSm="12" SpanXs="12">
                        <h1>Lookups</h1>
                        <h2>Board Length</h2>
                    </telerik:LayoutColumn>
                    <telerik:LayoutColumn Span="2" HiddenMd="true" HiddenSm="true" HiddenXs="true">
                        <img src="images/Thumbnails/Desert.jpg" />
                    </telerik:LayoutColumn>
                </Columns>
            </telerik:LayoutRow>
        </Rows>
    </telerik:RadPageLayout>
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteColumn="True"
        AutoGenerateEditColumn="True" DataSourceID="EntityDataSource1" ShowGroupPanel="True"
        AllowAutomaticDeletes="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" Skin="Office2010Blue">
        <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

        <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" ReorderColumnsOnClient="True">
            <Selecting AllowRowSelect="True" />
            <Scrolling AllowScroll="True" UseStaticHeaders="True" />
        </ClientSettings>

        <MasterTableView AutoGenerateColumns="False" DataKeyNames="c_id" DataSourceID="EntityDataSource1">
            <RowIndicatorColumn ShowNoSortIcon="False"></RowIndicatorColumn>

            <ExpandCollapseColumn ShowNoSortIcon="False"></ExpandCollapseColumn>

            <Columns>
                <telerik:GridBoundColumn DataField="c_id" DataType="System.Int32" FilterControlAltText="Filter c_id column" HeaderText="c_id" ReadOnly="True" ShowNoSortIcon="False" SortExpression="c_id" UniqueName="c_id">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="c_finish" FilterControlAltText="Filter c_finish column" HeaderText="c_finish" ShowNoSortIcon="False" SortExpression="c_finish" UniqueName="c_finish">
                </telerik:GridBoundColumn>
            </Columns>

            <EditFormSettings>
                <EditColumn ShowNoSortIcon="False"></EditColumn>
            </EditFormSettings>
        </MasterTableView>
    </telerik:RadGrid>

    <asp:EntityDataSource ID="EntityDataSource1" runat="server" ConnectionString="name=quotemachineEntities" DefaultContainerName="quotemachineEntities" EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="tbl_finish"></asp:EntityDataSource>

</asp:Content>
