<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/MasterPage.Master" CodeBehind="GradeForm.aspx.vb" Inherits="BL.QuoteMachine.GradeForm" %>
<%@ Register TagPrefix="telerik" Namespace="Telerik.Web.UI" Assembly="Telerik.Web.UI" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
      <link href="styles/grid.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <telerik:RadPageLayout runat="server" ID="JumbotronLayout" CssClass="jumbotron" GridType="Fluid">
        <Rows>
            <telerik:LayoutRow>
                <Columns>
                    <telerik:LayoutColumn Span="10" SpanMd="12" SpanSm="12" SpanXs="12">
                        <h1>Lookups</h1>
                        <h2>Finishers</h2>
                    </telerik:LayoutColumn>
                    <telerik:LayoutColumn Span="2" HiddenMd="true" HiddenSm="true" HiddenXs="true">
                        <img src="images/Thumbnails/Desert.jpg" />
                    </telerik:LayoutColumn>
                </Columns>
            </telerik:LayoutRow>
        </Rows>
    </telerik:RadPageLayout>
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
        <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" DataSourceID="EntityDataSource1" ShowGroupPanel="True">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

            <ClientSettings AllowColumnsReorder="True" AllowDragToGroup="True" ReorderColumnsOnClient="True">
                <Selecting AllowRowSelect="True" />
                <Scrolling AllowScroll="True" UseStaticHeaders="True" />
            </ClientSettings>

<MasterTableView AutoGenerateColumns="False" DataKeyNames="c_id" DataSourceID="EntityDataSource1">
<RowIndicatorColumn ShowNoSortIcon="False"></RowIndicatorColumn>

<ExpandCollapseColumn ShowNoSortIcon="False"></ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="c_id" DataType="System.Int32" FilterControlAltText="Filter c_id column" HeaderText="c_id" ReadOnly="True" ShowNoSortIcon="False" SortExpression="c_id" UniqueName="c_id">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_code" FilterControlAltText="Filter c_finisher_code column" HeaderText="c_finisher_code" ShowNoSortIcon="False" SortExpression="c_finisher_code" UniqueName="c_finisher_code">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_name" FilterControlAltText="Filter c_finisher_name column" HeaderText="c_finisher_name" ShowNoSortIcon="False" SortExpression="c_finisher_name" UniqueName="c_finisher_name">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_address" FilterControlAltText="Filter c_finisher_address column" HeaderText="c_finisher_address" ShowNoSortIcon="False" SortExpression="c_finisher_address" UniqueName="c_finisher_address">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_city" FilterControlAltText="Filter c_finisher_city column" HeaderText="c_finisher_city" ShowNoSortIcon="False" SortExpression="c_finisher_city" UniqueName="c_finisher_city">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_state" FilterControlAltText="Filter c_finisher_state column" HeaderText="c_finisher_state" ShowNoSortIcon="False" SortExpression="c_finisher_state" UniqueName="c_finisher_state">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_zip" FilterControlAltText="Filter c_finisher_zip column" HeaderText="c_finisher_zip" ShowNoSortIcon="False" SortExpression="c_finisher_zip" UniqueName="c_finisher_zip">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_contact_name" FilterControlAltText="Filter c_finisher_contact_name column" HeaderText="c_finisher_contact_name" ShowNoSortIcon="False" SortExpression="c_finisher_contact_name" UniqueName="c_finisher_contact_name">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_contact_email" FilterControlAltText="Filter c_finisher_contact_email column" HeaderText="c_finisher_contact_email" ShowNoSortIcon="False" SortExpression="c_finisher_contact_email" UniqueName="c_finisher_contact_email">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="c_finisher_contact_phone" FilterControlAltText="Filter c_finisher_contact_phone column" HeaderText="c_finisher_contact_phone" ShowNoSortIcon="False" SortExpression="c_finisher_contact_phone" UniqueName="c_finisher_contact_phone">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn ShowNoSortIcon="False"></EditColumn>
</EditFormSettings>
</MasterTableView>
                </telerik:RadGrid>
        
        <asp:EntityDataSource ID="EntityDataSource1" runat="server" ConnectionString="name=quotemachineEntities" DefaultContainerName="quotemachineEntities" EnableDelete="True" EnableFlattening="False" EnableInsert="True" EnableUpdate="True" EntitySetName="tbl_bl_grades"></asp:EntityDataSource>

</asp:Content>
