'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ListView

    '''<summary>
    '''JumbotronLayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JumbotronLayout As Global.Telerik.Web.UI.RadPageLayout

    '''<summary>
    '''RadButton0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton0 As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''RadListViewImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListViewImages As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''RadListViewArticles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadListViewArticles As Global.Telerik.Web.UI.RadListView

    '''<summary>
    '''RadLightBoxImageDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadLightBoxImageDetails As Global.Telerik.Web.UI.RadLightBox
End Class
